### PR TITLE
Potential fix for duplicated, html-only theme graphics in PDF

### LINKED ISSUE #233: Possible Graphics Conversion Problem
Graphic on Chapter 2, page 5 (https://docs.cisecurity.org/en/latest/maturity/maturities.html) appears to be broken during PDF conversion. 

Screenshot 2023-02-01 at 11 41 58 AM

### PR DESCRIPTION
**Pull request by jungshadow**
Fixes #233 (and possibly competes with #234).

### CODE REVIEW

**Comment by jungshadow** [comment]
@mike-garcia I realized that I was trying to fix this from the latex-side and not the ReST-side. I used the `only` directive to target only the html builder for dark images. The only bummer is that there isn't a good way to handle images with captions, as far as I can tell. But...I might think of something else later.

**Comment by mike-garcia** [comment]
Maturities looks good but mdbr doesn't show the dark image in dark mode. should is be :class: instead of :figclass:?

Also the RTD PR isn't producing a PDF, so I can't check that

**Comment by jungshadow** [comment]
@mike-garcia How's this?

**Comment by mike-garcia** [comment]
Still no good. Didn't seem to have any effect

Screenshot 2023-02-03 at 12 33 20

**Comment by mike-garcia** [comment]
Turns out it was file error. Issue resolved. Waiting on marketing for updated file

fixes #235 fixes #234

**Pull request merged**
